export enum ImgPaths {
  HTML = 'skills/html.png',
  CSS = 'skills/css.png',
  SCSS = 'skills/scss.png',
  JS = 'skills/js.png',
  TS = 'skills/ts.png',
  ANGULAR = 'skills/angular.png',
  RXJS = 'skills/rxjs.png',
  BOOTSTRAP = 'skills/bootstrap.png',
  PHP = 'skills/php.png',
  MYSQL = 'skills/mysql.png',
  POSTGRES = 'skills/pgadmin.png',
  FIREBASE = 'skills/firebase.png',
  JSON = 'skills/json.png',
  CSHARP = 'skills/cs.png',
  WPF = 'skills/wpf.png',
  UNITY = 'skills/unity.png',
  JAVA = 'skills/java.png',
  CPP = 'skills/cpp.png',
  PYTHON = 'skills/python.png',
  GIT = 'skills/git.png',
  GITHUB = 'skills/github.png',
  GIMP = 'skills/gimp.png',
  INKSCAPE = 'skills/inkscape.png',
}
